# NumPy and Pandas Exercises

In [32]:
import numpy as np
import pandas as pd

## 1. Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viết chương trình kiểm tra tất cả các phần tử trong mảng khác 0 (tìm hiểu hàm all của numpy)

In [33]:
np.random.seed(0) # for reproducibility
array_1 = np.random.randint(0, 21, size=(3, 3))
print("Mảng ngẫu nhiên 3x3:")
print(array_1)

all_non_zero = np.all(array_1 != 0)
print(f"Tất cả các phần tử trong mảng khác 0: {all_non_zero}")

Mảng ngẫu nhiên 3x3:
[[12 15  0]
 [ 3  3  7]
 [ 9 19 18]]
Tất cả các phần tử trong mảng khác 0: False

## 2. Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viết chương trình kiểm tra tồn tại một phần tử trong mảng khác 0 (tìm hiểu hàm any của numpy)

In [34]:
np.random.seed(1) # for reproducibility
array_2 = np.random.randint(0, 21, size=(3, 3))
print("Mảng ngẫu nhiên 3x3:")
print(array_2)

any_non_zero = np.any(array_2 != 0)
print(f"Tồn tại ít nhất một phần tử trong mảng khác 0: {any_non_zero}")

Mảng ngẫu nhiên 3x3:
[[ 5 11 12]
 [ 8  9 11]
 [ 5 15  0]]
Tồn tại ít nhất một phần tử trong mảng khác 0: True

## 3. Sinh viên tìm hiểu và viết chương trình sử dụng các hàm sau numpy.greater, numpy.greater_equal, numpy.less, và numpy.less_equal để so sánh 2 mảng 1 chiều, 2 chiều.

In [35]:
# Mảng 1 chiều
arr1_1d = np.array([1, 2, 3, 4, 5])
arr2_1d = np.array([5, 3, 2, 4, 1])

print("Mảng 1D 1:", arr1_1d)
print("Mảng 1D 2:", arr2_1d)
print("arr1_1d > arr2_1d:", np.greater(arr1_1d, arr2_1d))
print("arr1_1d >= arr2_1d:", np.greater_equal(arr1_1d, arr2_1d))
print("arr1_1d < arr2_1d:", np.less(arr1_1d, arr2_1d))
print("arr1_1d <= arr2_1d:", np.less_equal(arr1_1d, arr2_1d))

print("\n" + "-"*30 + "\n")

# Mảng 2 chiều
arr1_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2_2d = np.array([[3, 2, 1], [6, 5, 4]])

print("Mảng 2D 1:\n", arr1_2d)
print("Mảng 2D 2:\n", arr2_2d)
print("arr1_2d > arr2_2d:\n", np.greater(arr1_2d, arr2_2d))
print("arr1_2d >= arr2_2d:\n", np.greater_equal(arr1_2d, arr2_2d))
print("arr1_2d < arr2_2d:\n", np.less(arr1_2d, arr2_2d))
print("arr1_2d <= arr2_2d:\n", np.less_equal(arr1_2d, arr2_2d))

Mảng 1D 1: [1 2 3 4 5]
Mảng 1D 2: [5 3 2 4 1]
arr1_1d > arr2_1d: [False False  True False  True]
arr1_1d >= arr2_1d: [False False  True  True  True]
arr1_1d < arr2_1d: [ True  True False False False]
arr1_1d <= arr2_1d: [ True  True False  True False]

------------------------------

Mảng 2D 1:
 [[1 2 3]
 [4 5 6]]
Mảng 2D 2:
 [[3 2 1]
 [6 5 4]]
arr1_2d > arr2_2d:
 [[False False  True]
 [False False  True]]
arr1_2d >= arr2_2d:
 [[False  True  True]
 [False  True  True]]
arr1_2d < arr2_2d:
 [[ True False False]
 [ True False False]]
arr1_2d <= arr2_2d:
 [[ True  True False]
 [ True  True False]]

## 4. Viết chương trình tạo mảng gồm 10 số 1, 10 số 0 và 10 số 5

In [36]:
array_ones = np.ones(10, dtype=int)
array_zeros = np.zeros(10, dtype=int)
array_fives = np.full(10, 5, dtype=int)

combined_array = np.concatenate((array_ones, array_zeros, array_fives))
print("Mảng gồm 10 số 1, 10 số 0 và 10 số 5:")
print(combined_array)

Mảng gồm 10 số 1, 10 số 0 và 10 số 5:
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 5 5 5 5 5 5 5 5 5 5]

## 5. Viết chương trình tạo mảng số nguyên chẳn từ [30, 70]

In [37]:
even_numbers_array = np.arange(30, 71, 2) # Start at 30, end before 71, step by 2
print("Mảng số nguyên chẵn từ [30, 70]:")
print(even_numbers_array)

Mảng số nguyên chẵn từ [30, 70]:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]

## 6. Viết chương trình tạo ma trận đơn vị 3 x 3 (đường chéo chính bằng 1, các phần tử còn lại 0) (Tìm hiểu hàm identity của numpy)

In [38]:
identity_matrix = np.identity(3)
print("Ma trận đơn vị 3x3:")
print(identity_matrix)

Ma trận đơn vị 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

## 7. Viết chương trình tạo mảng 10 phần tử trong khoảng [15, 55]. In các giá trị ngoài trừ phần tử đầu và cuối

In [39]:
np.random.seed(2) # for reproducibility
array_7 = np.random.randint(15, 56, size=10) # 56 because randint is exclusive of high value
print("Mảng gốc:", array_7)

print("Các giá trị ngoài trừ phần tử đầu và cuối:", array_7[1:-1])

Mảng gốc: [55 30 23 37 33 26 55 22 49 46]
Các giá trị ngoài trừ phần tử đầu và cuối: [30 23 37 33 26 55 22 49]

## 8. Viết chương trình tạo mảng 20 phần tử trong khoảng [0, 20] và đổi dấu những số nằm trong khoảng [9, 15]

In [40]:
np.random.seed(3) # for reproducibility
array_8 = np.random.randint(0, 21, size=20)
print("Mảng gốc:", array_8)

# Tạo một bản sao để không sửa đổi mảng gốc trực tiếp
modified_array_8 = array_8.copy()

# Xác định các phần tử trong khoảng [9, 15]
condition = (modified_array_8 >= 9) & (modified_array_8 <= 15)

# Đổi dấu các phần tử thỏa mãn điều kiện
modified_array_8[condition] = -modified_array_8[condition]

print("Mảng sau khi đổi dấu:", modified_array_8)

Mảng gốc: [10  3  8  0 19 10 11  9 10  6  0 20 12  7 14 17  2  2  1 19]
Mảng sau khi đổi dấu: [-10   3   8   0  19 -10 -11  -9 -10   6   0  20 -12   7 -14  17   2   2
   1  19]

## 9. Viết chương trình tạo ma trận 3 x 4 và mỗi phần tử có giá trị [10, 21]

In [41]:
np.random.seed(4) # for reproducibility
matrix_9 = np.random.randint(10, 22, size=(3, 4)) # 22 because randint is exclusive of high value
print("Ma trận 3x4 với các phần tử trong khoảng [10, 21]:\n", matrix_9)

Ma trận 3x4 với các phần tử trong khoảng [10, 21]:
 [[20 17 15 11]
 [18 17 18 12]
 [19 20 17 17]]

## 10. Viết chương trình tạo ma trận 10 x 10, các phần tử ở biên có giá trị 1, các phần tử bên trong có giá trị 0

In [42]:
matrix_10 = np.zeros((10, 10), dtype=int)
matrix_10[0, :] = 1 # Dòng đầu tiên
matrix_10[-1, :] = 1 # Dòng cuối cùng
matrix_10[:, 0] = 1 # Cột đầu tiên
matrix_10[:, -1] = 1 # Cột cuối cùng
print("Ma trận 10x10 với biên là 1 và bên trong là 0:\n", matrix_10)

Ma trận 10x10 với biên là 1 và bên trong là 0:
 [[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]

## 11. Viết chương trình tạo ma trận 5 x 5, các phần tử ở đường chéo chính là 1, 2, 3, 4, 5. (tìm hiểu hàm diag của numpy)

In [43]:
diagonal_elements = np.array([1, 2, 3, 4, 5])
matrix_11 = np.diag(diagonal_elements)
print("Ma trận 5x5 với đường chéo chính là 1, 2, 3, 4, 5:\n", matrix_11)

Ma trận 5x5 với đường chéo chính là 1, 2, 3, 4, 5:
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]

## 12. Viết chương trình tạo mảng 3 x 3 x 3 và tính tổng theo mỗi dòng, mỗi cột. (tìm hiểu hàm sum của numpy)

In [44]:
np.random.seed(5) # for reproducibility
array_12 = np.random.randint(0, 10, size=(3, 3, 3))
print("Mảng 3x3x3:\n", array_12)

# Tính tổng theo mỗi trục (axis)
# axis=0: tổng theo 'sâu' (kết quả là 3x3)
# axis=1: tổng theo 'dòng' (kết quả là 3x3)
# axis=2: tổng theo 'cột' (kết quả là 3x3)

print("\nTổng theo trục 0 (sâu):\n", np.sum(array_12, axis=0))
print("\nTổng theo trục 1 (dòng):\n", np.sum(array_12, axis=1))
print("\nTổng theo trục 2 (cột):\n", np.sum(array_12, axis=2))

Mảng 3x3x3:
 [[[3 6 6]
  [0 9 8]
  [4 7 0]]

 [[0 7 1]
  [5 7 0]
  [1 4 6]]

 [[2 9 9]
  [9 9 1]
  [2 7 0]]]

Tổng theo trục 0 (sâu):
 [[ 5 22 16]
 [14 25  9]
 [ 7 18  6]]

Tổng theo trục 1 (dòng):
 [[ 7 22 14]
 [ 6 18  7]
 [13 25 10]]

Tổng theo trục 2 (cột):
 [[15 17 11]
 [ 8 12 11]
 [20 19  9]]

## 13. Tạo 2 vector ngẫu nhiên 10 phần tử. Thực hiện inner product (np.dot)

In [45]:
np.random.seed(6) # for reproducibility
vector1 = np.random.rand(10)
vector2 = np.random.rand(10)

print("Vector 1:", vector1)
print("Vector 2:", vector2)

inner_product = np.dot(vector1, vector2)
print("Tích vô hướng (Inner Product):", inner_product)

Vector 1: [0.89286015 0.33197981 0.82122912 0.04169663 0.10765668 0.59505206
 0.52981736 0.41880743 0.33540785 0.62251943]
Vector 2: [0.43814143 0.73588211 0.51803641 0.5788586  0.6453551  0.99022427
 0.8198582  0.41320093 0.87626766 0.82375943]
Tích vô hướng (Inner Product): 3.1579118730110958

## 14. Tạo ma trận A= 4 x 3 và vector y gồm 3 phần tử ngẫu nhiên. Thêm vector y vào từng dòng của ma trận A

In [46]:
np.random.seed(7) # for reproducibility
matrix_A = np.random.randint(0, 10, size=(4, 3))
vector_y = np.random.randint(0, 10, size=3)

print("Ma trận A:\n", matrix_A)
print("Vector y:", vector_y)

# Thêm vector y vào từng dòng của ma trận A
# NumPy Broadcasting sẽ tự động thêm vector y vào mỗi dòng của A
result_matrix = matrix_A + vector_y

print("\nMa trận sau khi thêm vector y vào mỗi dòng:\n", result_matrix)

Ma trận A:
 [[4 9 6]
 [3 3 7]
 [7 9 7]
 [8 9 8]]
Vector y: [7 6 4]

Ma trận sau khi thêm vector y vào mỗi dòng:
 [[11 15 10]
 [10  9 11]
 [14 15 11]
 [15 15 12]]

## 15. Viết chương trình Pandas để cộng, trừ, nhân, chia 2 Series : [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]

In [47]:
series1 = pd.Series([2, 4, 6, 8, 10])
series2 = pd.Series([1, 3, 5, 7, 10])

print("Series 1:\n", series1)
print("Series 2:\n", series2)

print("\nCộng:\n", series1 + series2)
print("Trừ:\n", series1 - series2)
print("Nhân:\n", series1 * series2)
print("Chia:\n", series1 / series2)

Series 1:
 0     2
1     4
2     6
3     8
4    10
dtype: int64
Series 2:
 0     1
1     3
2     5
3     7
4    10
dtype: int64

Cộng:
 0     3
1     7
2    11
3    15
4    20
dtype: int64
Trừ:
 0    1
1    1
2    1
3    1
4    0
dtype: int64
Nhân:
 0      2
1     12
2     30
3     56
4    100
dtype: int64
Chia:
 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.000000
dtype: float64

## 16. Viết chương trình Pandas chuyển đổi cột đầu tiên thành Series (Tìm hiểu thuộc tính ix của pandas)

In [48]:
data = {'col1': [10, 20, 30, 40],
        'col2': [100, 200, 300, 400],
        'col3': [1, 2, 3, 4]}
df_16 = pd.DataFrame(data)
print("DataFrame gốc:\n", df_16)

# Thuộc tính .ix đã không còn được dùng. Thay vào đó, ta có thể chọn cột trực tiếp hoặc dùng .iloc
# Cách 1: Chọn cột bằng tên
series_from_col1 = df_16['col1']
print("\nCột đầu tiên ('col1') dưới dạng Series:\n", series_from_col1)
print("Kiểu dữ liệu của series_from_col1:", type(series_from_col1))

# Cách 2: Sử dụng .iloc để chọn cột theo vị trí (cột đầu tiên là index 0)
series_from_col_index0 = df_16.iloc[:, 0]
print("\nCột đầu tiên (index 0) dưới dạng Series (dùng .iloc):\n", series_from_col_index0)
print("Kiểu dữ liệu của series_from_col_index0:", type(series_from_col_index0))

DataFrame gốc:
    col1  col2  col3
0    10   100     1
1    20   200     2
2    30   300     3
3    40   400     4

Cột đầu tiên ('col1') dưới dạng Series:
 0    10
1    20
2    30
3    40
Name: col1, dtype: int64
Kiểu dữ liệu của series_from_col1: <class 'pandas.core.series.Series'>

Cột đầu tiên (index 0) dưới dạng Series (dùng .iloc):
 0    10
1    20
2    30
3    40
Name: col1, dtype: int64
Kiểu dữ liệu của series_from_col_index0: <class 'pandas.core.series.Series'>

## 17. Viết chương trình Pandas sắp xếp theo cột của DataFrame 4 x 3 ngẫu nhiên

In [49]:
np.random.seed(8) # for reproducibility
df_17 = pd.DataFrame(np.random.randint(0, 100, size=(4, 3)), columns=['A', 'B', 'C'])
print("DataFrame gốc:\n", df_17)

# Sắp xếp DataFrame theo cột 'B'
sorted_df = df_17.sort_values(by='B')
print("\nDataFrame sau khi sắp xếp theo cột 'B':\n", sorted_df)

DataFrame gốc:
     A   B   C
0  67  84   5
1  90   8  83
2  63  48  85
3  60  49  74

DataFrame sau khi sắp xếp theo cột 'B':
     A   B   C
1  90   8  83
2  63  48  85
3  60  49  74
0  67  84   5

## 18. Viết chương trình Pandas thay đổi index của một Series (dùng pandas.reindex)

In [50]:
series_18 = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print("Series gốc:\n", series_18)

# Thay đổi index bằng reindex
new_index = ['d', 'b', 'e', 'a', 'f']
reindexed_series = series_18.reindex(new_index)
print("\nSeries sau khi thay đổi index:\n", reindexed_series)

Series gốc:
 a    10
b    20
c    30
d    40
dtype: int64

Series sau khi thay đổi index:
 d    40.0
b    20.0
e     NaN
a    10.0
f     NaN
dtype: float64

## 19. Viết chương trình Pandas tìm những phần tử trong Series x mà không có trong Series y (Tìm hiểu hàm isin của pandas)

In [51]:
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])

print("sr1:\n", sr1)
print("sr2:\n", sr2)

# Tìm các phần tử trong sr1 không có trong sr2
items_not_in_sr2 = sr1[~sr1.isin(sr2)]
print("\nItems of sr1 not present in sr2:\n", items_not_in_sr2)

sr1:
 0    1
1    2
2    3
3    4
4    5
dtype: int64
sr2:
 0     2
1     4
2     6
3     8
4    10
dtype: int64

Items of sr1 not present in sr2:
 0    1
2    3
4    5
dtype: int64

## 20. Tìm hiểu phép toán numpy.union1d, numpy.intersect1d (hội, giao) và viết chương trình minh họa 2 hàm này trên 2 Series x, y ngẫu nhiên có 20 phần tử

In [52]:
np.random.seed(9) # for reproducibility
series_x_20 = pd.Series(np.random.randint(0, 30, size=20))
series_y_20 = pd.Series(np.random.randint(15, 45, size=20))

print("Series x (20 phần tử):\n", series_x_20)
print("\nSeries y (20 phần tử):\n", series_y_20)

# Sử dụng np.union1d cho phép hội
union_result = np.union1d(series_x_20, series_y_20)
print("\nPhép hội (Union) của Series x và y:\n", union_result)

# Sử dụng np.intersect1d cho phép giao
intersect_result = np.intersect1d(series_x_20, series_y_20)
print("\nPhép giao (Intersection) của Series x và y:\n", intersect_result)

Series x (20 phần tử):
 0     28
1     21
2     22
3     24
4     27
5     22
6     29
7      1
8     22
9     20
10    27
11     8
12    26
13    17
14    24
15    21
16    27
17     1
18    29
19    28
dtype: int64

Series y (20 phần tử):
 0     15
1     43
2     29
3     42
4     39
5     25
6     39
7     44
8     25
9     43
10    39
11    27
12    33
13    37
14    39
15    16
16    39
17    18
18    26
19    20
dtype: int64

Phép hội (Union) của Series x và y:
 [ 1  8 15 16 17 18 20 21 22 24 25 26 27 28 29 33 37 39 42 43 44]

Phép giao (Intersection) của Series x và y:
 [20 26 27 29]

## 21. Viết chương trình Pandas thêm series y vào series x theo chiều dọc (vertical), chiều ngang (horizontal) (Tìm hiểu hàm append và concat của pandas)

In [53]:
series_x_21 = pd.Series(range(10))
series_y_21 = pd.Series([chr(ord('p') + i) for i in range(10)], index=range(10))

print("Series x:\n", series_x_21)
print("\nSeries y:\n", series_y_21)

# Thêm series y vào series x theo chiều dọc (vertical)
# append đã bị deprecated, sử dụng pd.concat thay thế
vertical_concat = pd.concat([series_x_21, series_y_21], axis=0)
print("\nThêm series y vào series x theo chiều dọc (Vertical concat):\n", vertical_concat)

# Thêm series y vào series x theo chiều ngang (horizontal)
horizontal_concat = pd.concat([series_x_21, series_y_21], axis=1)
print("\nThêm series y vào series x theo chiều ngang (Horizontal concat):\n", horizontal_concat)

Series x:
 0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

Series y:
 0    p
1    q
2    r
3    s
4    t
5    u
6    v
7    w
8    x
9    y
dtype: object

Thêm series y vào series x theo chiều dọc (Vertical concat):
 0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
0    p
1    q
2    r
3    s
4    t
5    u
6    v
7    w
8    x
9    y
dtype: object

Thêm series y vào series x theo chiều ngang (Horizontal concat):
    0  1
0  0  p
1  1  q
2  2  r
3  3  s
4  4  t
5  5  u
6  6  v
7  7  w
8  8  x
9  9  y

## 22. Viết chương trình Pandas tạo và hiển thị dữ liệu DataFrame sau

In [54]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew',
                      'Laura', 'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df_exam = pd.DataFrame(exam_data, index=labels)
print("DataFrame exam_data:\n")
display(df_exam)

DataFrame exam_data:

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

## 23. Từ bài 22, cho biết 3 dòng đầu tiên

In [55]:
print("3 dòng đầu tiên của DataFrame:\n")
display(df_exam.head(3))

3 dòng đầu tiên của DataFrame:

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

## 24. Từ bài 22, chọn cột ‘name’ và ‘score’

In [56]:
print("Các cột 'name' và 'score':\n")
display(df_exam[['name', 'score']])

Các cột 'name' và 'score':

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

## 25. Từ bài 22, chọn những dòng có attemps > 2

In [57]:
print("Những dòng có 'attempts' > 2:\n")
display(df_exam[df_exam['attempts'] > 2])

Những dòng có 'attempts' > 2:

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

## 26. Từ bài 22, cho biết số dòng, số cột của DataFrame

In [58]:
num_rows, num_cols = df_exam.shape
print(f"Số dòng của DataFrame: {num_rows}")
print(f"Số cột của DataFrame: {num_cols}")

Số dòng của DataFrame: 10
Số cột của DataFrame: 4

## 27. Từ bài 22, cho biết những dòng có score là NaN (tìm hiểu hàm isnull của pandas)

In [59]:
print("Những dòng có 'score' là NaN:\n")
display(df_exam[df_exam['score'].isnull()])

Những dòng có 'score' là NaN:

    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no

## 28. Từ bài 22, cho biết những dòng có score trong khoảng (15, 20) (tìm hiểu hàm between của pandas)

In [60]:
print("Những dòng có 'score' trong khoảng (15, 20) (không bao gồm 15 và 20):\n")
display(df_exam[df_exam['score'].between(15, 20, inclusive='neither')])

print("\nNhững dòng có 'score' trong khoảng [15, 20] (bao gồm 15 và 20):\n")
display(df_exam[df_exam['score'].between(15, 20, inclusive='both')])

Những dòng có 'score' trong khoảng (15, 20) (không bao gồm 15 và 20):

        name  score  attempts qualify
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes

Những dòng có 'score' trong khoảng [15, 20] (bao gồm 15 và 20):

        name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes

## 29. Từ bài 22, cho biết những dòng có attempt > 2 và score trong khoảng (15, 20)

In [61]:
print("Những dòng có 'attempts' > 2 và 'score' trong khoảng (15, 20):\n")
condition_29 = (df_exam['attempts'] > 2) & (df_exam['score'].between(15, 20, inclusive='neither'))
display(df_exam[condition_29])

Những dòng có 'attempts' > 2 và 'score' trong khoảng (15, 20):

Empty DataFrame
Columns: [name, score, attempts, qualify]
Index: []

## 30. Từ bài 22, cho biết những thay đổi giá trị dòng ‘d’, cột score là 19 (tìm hiểu hàm loc của pandas)

In [62]:
print("DataFrame gốc trước khi thay đổi:\n")
display(df_exam)

df_exam.loc['d', 'score'] = 19

print("\nDataFrame sau khi thay đổi giá trị 'score' của dòng 'd' thành 19:\n")
display(df_exam)

DataFrame gốc trước khi thay đổi:

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

DataFrame sau khi thay đổi giá trị 'score' của dòng 'd' thành 19:

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   19.0         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

### Các bài tập NumPy & Pandas với dữ liệu nhập từ bàn phím

#### Ví dụ Bài 1 & 2: Kiểm tra mảng với kích thước tùy chỉnh

In [ ]:
import numpy as np

# Nhập kích thước mảng
rows = int(input("Nhập số hàng: "))
cols = int(input("Nhập số cột: "))
low = int(input("Nhập giá trị nhỏ nhất: "))
high = int(input("Nhập giá trị lớn nhất: "))

# Tạo mảng
user_array = np.random.randint(low, high + 1, size=(rows, cols))
print("\nMảng vừa tạo:")
print(user_array)

# Kiểm tra
print(f"Tất cả phần tử khác 0: {np.all(user_array != 0)}")
print(f"Tồn tại phần tử khác 0: {np.any(user_array != 0)}")

#### Ví dụ Bài 15: Phép tính trên Series với dữ liệu nhập từ bàn phím

In [ ]:
import pandas as pd

def get_series_input(name):
    input_str = input(f"Nhập các số cho {name}, cách nhau bởi dấu phẩy: ")
    data = [float(x.strip()) for x in input_str.split(',')]
    return pd.Series(data)

sr_a = get_series_input("Series A")
sr_b = get_series_input("Series B")

if len(sr_a) == len(sr_b):
    results = pd.DataFrame({
        'A': sr_a,
        'B': sr_b,
        'A + B': sr_a + sr_b,
        'A - B': sr_a - sr_b,
        'A * B': sr_a * sr_b,
        'A / B': sr_a / sr_b
    })
    display(results)
else:
    print("Lỗi: Hai Series phải có cùng độ dài để thực hiện phép tính.")

#### Ví dụ Bài 25: Lọc DataFrame theo điều kiện nhập vào

In [ ]:
# Sử dụng df_exam đã tạo ở bài 22
threshold = int(input("Nhập số lần thử (attempts) tối thiểu để lọc: "))

filtered_df = df_exam[df_exam['attempts'] > threshold]
print(f"\nCác sinh viên có số lần thử > {threshold}:")
display(filtered_df)